set.seed(1)
x <- load("/Users/shin-ichironakayama/Dropbox/r_practice/projectR/catch_data.rda")
test_num <- 500
mse1 <- c()
mse2 <- c()
mse3 <- c()
mse4 <- c()
mse5 <- c()
for(i in 1:100)
{
  all <- c(1:nrow(catch_data))
  test <- sample(all, test_num)
  training <- all[-test]
  test_data <- catch_data[test,]
  training_data <- catch_data[training,]
  res1 <- lm(log(catch) ~  1, data=training_data)
  pred1 <- predict(res1, newdata=test_data)
  res2 <- lm(log(catch) ~ temp, data=training_data)
  pred2 <- predict(res2, newdata=test_data)
  res3 <- lm(log(catch) ~ vessel - 1, data=training_data)
  pred3 <- predict(res3, newdata=test_data)
  res4 <- lm(log(catch) ~ vessel + temp - 1, data=training_data)
  pred4 <- predict(res4, newdata=test_data)
  res5 <- lm(log(catch) ~ vessel + temp + vessel:temp - 1, data=training_data)
  pred5 <- predict(res5, newdata=test_data)
  err1 <- pred1 - log(test_data$catch)
  err2 <- pred2 - log(test_data$catch)
  err3 <- pred3 - log(test_data$catch)
  err4 <- pred4 - log(test_data$catch)
  err5 <- pred5 - log(test_data$catch)
  mse1 <- c(mse1, mean(err1^2))
  mse2 <- c(mse2, mean(err2^2))
  mse3 <- c(mse3, mean(err3^2))
  mse4 <- c(mse4, mean(err4^2))
  mse5 <- c(mse5, mean(err5^2))
}
boxplot(mse1, mse2, mse3, mse4, mse5)
mean(mse4)
mean(mse5)
t.test(mse4, mse5, paired = T)

res1 <- lm(log(catch) ~ vessel + temp - 1, data=catch_data)
res2 <- lm(log(catch) ~ vessel + temp + vessel:temp - 1, data=catch_data)
logLik(res1)
logLik(res2)
AIC(res1)
AIC(res2)